name: Asana Release Workflow

on:
  release:
    types: [ created ]

jobs:
  asana_release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Asana Workflow
      run: node scripts/release.js
